### ISSUE TITLE
a < b is broken

### ISSUE THREAD

**Issue by mwz921804620** [mathquill/mathquill#883] opened 2020-01-09 02:53 UTC
when I use MQ.StaticMath(a<b), I can not find velue.

**Comment by ChristopherHX** [comment] 2020-07-09 10:51
I don't think it broken use `MQ.StaticMath('a<b')`, you forget the string literal `'a<b'` or `"a<b"`
JS will execute this as it is javascript code, `a<b` compares a and b before passing it to mathquill

**Comment by jaltekruse** [comment] 2021-04-21 12:32
Not a bug with Mathquill, so I'm going to close this. Thanks for providing an answer to the question @ChristopherHX!

**Closed** 2021-04-21 12:32 UTC
