### ISSUE TITLE
Strange behaviour with text{}

### ISSUE THREAD

**Issue by jlchereau** [mathquill/mathquill#755] opened 2017-06-17 17:09 UTC
Type `\text{` or `\text{}` and get:

![image](https://user-images.githubusercontent.com/2556751/27254792-f15ae6b8-5387-11e7-8830-8854e4091c40.png)

**Comment by bsuh** [comment] 2017-06-29 20:14
Caused by https://github.com/mathquill/mathquill/commit/5c7bfe5749bbf0ffec897367cd198ed4337e73f8

**Comment by laughinghan** [comment] 2017-08-15 04:52
nice catch @bsuh, repro'd on http://many-worlds.glitch.me/mathquill/mathquill/branch/master/test/demo.html

**Comment by laughinghan** [comment] 2017-08-15 05:00
Wait no it wasn't caused by that, that commit isn't even in `master` and in fact that commit fixes this issue: http://many-worlds.glitch.me/mathquill/mathquill/commit/7b3139ab293ce6c544b0af293553ca4a53372165/test/demo.html

This issue is a duplicate of #709, which is fixed by that commit (PR: #767).

**Closed by laughinghan** 2017-08-15 05:00 UTC

**Comment by bsuh** [comment] 2017-08-18 03:47
@laughinghan Oh sorry. I thought it was on master already and a new problem caused by the fix. Not familiar with the development process. When would the fix land on master?

**Comment by WUKS87** [comment] 2019-12-24 11:25
@laughinghan I see this issue still. Is there a chance it will be fixed? Thanks

**Comment by WUKS87** [comment] 2019-12-25 11:30
I solved it by using code from commit. Thanks
